### ISSUE TITLE
Permissions after copy (binary easyblock)

### ISSUE THREAD

**Issue by cmeesters** [easybuilders/easybuild#415] opened 2018-02-22 07:13 UTC
Hi,

After installing a simple helper script with the following permissions:
-rwxr-xr-x
we end up with those permissions after the installation:
-rwx-w----
Clearly ordinary users are not allowed to execute or read the script.

We are using the binary easyblock (eb version is 3.5.0) and the code of this block states in line 85
os.chmod(dst, stat.S_IRWXU)
I wonder whether this should rather be omitted and preserve the previous (whatever they are) permission settings or grant any user read and execution permissions per default (os.chmod(dst, stat.S_IRWXU | stat.S_IROTH | stat.S_IXOTH). 

Emphasis if on "I wonder", because perhaps the intention was different? Then, what would be the appropriate solution?

Best regards,
Christian

**Comment by boegel** [comment] 2018-02-22 21:18
@cmeesters This looks like a duplicate of #1259?

**Comment by cmeesters** [comment] 2018-02-23 03:51
Hi,
thanks for looking into this. As for your question: I do not know - is there any issue number >> 415?
Christian

**Comment by boegel** [comment] 2018-02-23 07:42
Sorry, the issue is in another repository, I meant to refer to https://github.com/easybuilders/easybuild-easyblocks/issues/1259

**Comment by cmeesters** [comment] 2018-02-23 08:08
Then indeed, this issue is a duplicate and I've been posting to the wrong repo. Sorry.

**Comment by boegel** [comment] 2018-02-23 08:18
No need to apologise, I know very well the many issues spread across different repos are sometimes confusing (but it also helps keeping things manageable).
Let's follow up in https://github.com/easybuilders/easybuild-easyblocks/issues/1259

**Closed by boegel** 2018-02-23 08:18 UTC
Labels: bug report
