### ISSUE TITLE
 Failed to move contents of

### ISSUE THREAD

**Issue by chenshixinnb** [easybuilders/easybuild#769] opened 2021-12-28 12:49 UTC
```
== 2021-12-28 12:34:31,080 easyblock.py:1980 INFO Using /public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304/l_mpi_2019.9.304/ as start dir
== 2021-12-28 12:34:31,080 build_log.py:265 INFO configuring...
== 2021-12-28 12:34:31,080 easyblock.py:3701 INFO Starting configure step
== 2021-12-28 12:34:31,080 easyconfig.py:1686 INFO Generating template values...
== 2021-12-28 12:34:31,080 easyconfig.py:1705 INFO Template values: arch='x86_64', bitbucket_account='impi', builddir='/public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304', github_account='impi', installdir='/public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304', module_name='impi/2019.9.304-iccifort-2020.4.304', name='impi', nameletter='i', nameletterlower='i', namelower='impi', parallel='16', toolchain_name='iccifort', toolchain_version='2020.4.304', version='2019.9.304', version_major='2019', version_major_minor='2019.9', version_minor='9', versionprefix='', versionsuffix=''
== 2021-12-28 12:34:31,081 easyblock.py:3709 INFO Running method configure_step part of step configure
== 2021-12-28 12:34:31,082 build_log.py:265 INFO building...
== 2021-12-28 12:34:31,082 easyblock.py:3701 INFO Starting build step
== 2021-12-28 12:34:31,082 easyconfig.py:1686 INFO Generating template values...
== 2021-12-28 12:34:31,082 easyconfig.py:1705 INFO Template values: arch='x86_64', bitbucket_account='impi', builddir='/public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304', github_account='impi', installdir='/public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304', module_name='impi/2019.9.304-iccifort-2020.4.304', name='impi', nameletter='i', nameletterlower='i', namelower='impi', parallel='16', toolchain_name='iccifort', toolchain_version='2020.4.304', version='2019.9.304', version_major='2019', version_major_minor='2019.9', version_minor='9', versionprefix='', versionsuffix=''
== 2021-12-28 12:34:31,083 easyblock.py:3709 INFO Running method build_step part of step build
== 2021-12-28 12:34:31,083 build_log.py:265 INFO testing...
== 2021-12-28 12:34:31,083 easyblock.py:3701 INFO Starting test step
== 2021-12-28 12:34:31,083 easyconfig.py:1686 INFO Generating template values...
== 2021-12-28 12:34:31,083 easyconfig.py:1705 INFO Template values: arch='x86_64', bitbucket_account='impi', builddir='/public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304', github_account='impi', installdir='/public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304', module_name='impi/2019.9.304-iccifort-2020.4.304', name='impi', nameletter='i', nameletterlower='i', namelower='impi', parallel='16', toolchain_name='iccifort', toolchain_version='2020.4.304', version='2019.9.304', version_major='2019', version_major_minor='2019.9', version_minor='9', versionprefix='', versionsuffix=''
== 2021-12-28 12:34:31,083 easyblock.py:3709 INFO Running method test_step part of step test
== 2021-12-28 12:34:31,083 build_log.py:265 INFO installing...
== 2021-12-28 12:34:31,083 easyblock.py:3701 INFO Starting install step
== 2021-12-28 12:34:31,083 easyconfig.py:1686 INFO Generating template values...
== 2021-12-28 12:34:31,084 easyconfig.py:1705 INFO Template values: arch='x86_64', bitbucket_account='impi', builddir='/public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304', github_account='impi', installdir='/public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304', module_name='impi/2019.9.304-iccifort-2020.4.304', name='impi', nameletter='i', nameletterlower='i', namelower='impi', parallel='16', toolchain_name='iccifort', toolchain_version='2020.4.304', version='2019.9.304', version_major='2019', version_major_minor='2019.9', version_minor='9', versionprefix='', versionsuffix=''
== 2021-12-28 12:34:31,084 easyblock.py:3709 INFO Running method stage_install_step part of step install
== 2021-12-28 12:34:31,084 easyblock.py:3709 INFO Running method make_installdir part of step install
== 2021-12-28 12:34:31,084 easyblock.py:1029 INFO Found old directory /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304
== 2021-12-28 12:34:31,084 filetools.py:380 INFO Path /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304 successfully removed.
== 2021-12-28 12:34:31,084 easyblock.py:1037 INFO Removed old directory /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304
== 2021-12-28 12:34:31,084 easyblock.py:1049 INFO Cleaning only, no actual creation of /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304, only verification/defining of dirname /public/software/.local/easybuild/software/impi
== 2021-12-28 12:34:31,084 easyblock.py:3709 INFO Running method install_step part of step install
== 2021-12-28 12:34:31,084 filetools.py:245 INFO Overwriting existing file /public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304/l_mpi_2019.9.304/silent.cfg
== 2021-12-28 12:34:31,085 filetools.py:1875 INFO Creating directory /public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304/l_mpi_2019.9.304/mytmpdir (parents: True, set_gid: False, sticky: False)
== 2021-12-28 12:34:31,085 environment.py:91 INFO Environment variable LOCAL_INSTALL_VERBOSE set to 1 (previously undefined)
== 2021-12-28 12:34:31,085 environment.py:91 INFO Environment variable VERBOSE_MODE set to 1 (previously undefined)
== 2021-12-28 12:34:31,085 environment.py:91 INFO Environment variable INSTALL_PATH set to /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304 (previously undefined)
== 2021-12-28 12:34:31,085 run.py:233 INFO running cmd:  ./install.sh  -s /public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304/l_mpi_2019.9.304/silent.cfg
== 2021-12-28 12:34:38,509 run.py:623 INFO cmd " ./install.sh  -s /public/software/.local/easybuild/build/impi/2019.9.304/iccifort-2020.4.304/l_mpi_2019.9.304/silent.cfg " exited with exit code 0 and output:

== 2021-12-28 12:34:38,536 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/lib/python3.6/site-packages/easybuild/base/exceptions.py:124 in __init__): Failed to move contents of /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304/impi/2019.9.304 to /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304: [Errno 2] No such file or directory: '/public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304/impi/2019.9.304' (at easybuild/lib/python3.6/site-packages/easybuild/easyblocks/generic/intelbase.py:480 in move_after_install)
== 2021-12-28 12:34:38,536 build_log.py:265 INFO ... (took 7 secs)
== 2021-12-28 12:34:38,537 filetools.py:1976 INFO Removing lock /public/software/.local/easybuild/software/.locks/_public_software_.local_easybuild_software_impi_2019.9.304-iccifort-2020.4.304.lock...
== 2021-12-28 12:34:38,537 filetools.py:380 INFO Path /public/software/.local/easybuild/software/.locks/_public_software_.local_easybuild_software_impi_2019.9.304-iccifort-2020.4.304.lock successfully removed.
== 2021-12-28 12:34:38,537 filetools.py:1980 INFO Lock removed: /public/software/.local/easybuild/software/.locks/_public_software_.local_easybuild_software_impi_2019.9.304-iccifort-2020.4.304.lock
== 2021-12-28 12:34:38,537 easyblock.py:4032 WARNING build failed (first 300 chars): Failed to move contents of /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304/impi/2019.9.304 to /public/software/.local/easybuild/software/impi/2019.9.304-iccifort-2020.4.304: [Errno 2] No such file or directory: '/public/software/.local/easybuild/software/impi/2019.9.30
== 2021-12-28 12:34:38,537 easyblock.py:318 INFO Closing log for application name impi version 2019.9.304
```

**Comment by chenshixinnb** [comment] 2021-12-28 12:50
please help me，thanks
build prefix=/public/software/.local/easybuild/software

**Comment by chenshixinnb** [comment] 2021-12-28 12:54
Command: eb CP2K-7.1-intel-2020b.eb --robot --allow-use-as-root --insecure-download;
Error in "impi-2019.9.304-iccifort-2020.4.304.eb" step.

**Comment by boegel** [comment] 2022-01-03 10:46
@chenshixinnb I'll close this issue, since it's a duplicate of https://github.com/easybuilders/easybuild-easyconfigs/issues/14642, let's follow up there...

**Closed by boegel** 2022-01-03 10:46 UTC
Labels: problem report
