### ISSUE TITLE
foss2021b build on ubuntu 22.04

### ISSUE THREAD

**Issue by elc42** [easybuilders/easybuild#823] opened 2022-09-14 20:53 UTC
== processing EasyBuild easyconfig /home/elcar/.local/easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-11.2.0.eb
== building and installing libreadline/8.1-GCCcore-11.2.0...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== FAILED: Installation ended unsuccessfully (build directory: /home/elcar/.local/easybuild/build/libreadline/8.1/GCCcore-11.2.0): build failed (first 300 chars): cmd "/home/elcar/.local/easybuild/sources/generic/eb_v4.6.1/ConfigureMake/config.guess" exited with exit code 1 and output:
/bin/bash: /home/elcar/.local/easybuild/software/ncurses/6.2-GCCcore-11.2.0/lib/libtinfo.so.6: version `NCURSES6_TINFO_5.0.19991023' not found (required by /bin/bash)
 (took 0 secs)
== Results of the build can be found in the log file(s) /tmp/eb-_1ksi_u7/easybuild-libreadline-8.1-20220914.225341.RfCtq.log
ERROR: Build of /home/elcar/.local/easybuild/easyconfigs/l/libreadline/libreadline-8.1-GCCcore-11.2.0.eb failed (err: 'build failed (first 300 chars): cmd "/home/elcar/.local/easybuild/sources/generic/eb_v4.6.1/ConfigureMake/config.guess" exited with exit code 1 and output:\n/bin/bash: /home/elcar/.local/easybuild/software/ncurses/6.2-GCCcore-11.2.0/lib/libtinfo.so.6: version `NCURSES6_TINFO_5.0.19991023\' not found (required by /bin/bash)\n')

**Comment by guignont** [comment] 2022-09-16 07:53
Does it means that libtinfo.so.6 provided by foss2021b is not compatible with ubuntu provided bash ?
Is it safe to manually remplace "easybuild/software/ncurses/6.2-GCCcore-11.2.0/lib/libtinfo.so.6" with libtinfo.so.6 provided by ubuntu ?

**Comment by branfosj** [comment] 2022-09-16 08:56
> @Micket I'm a bit nervous that [easybuilders/easybuild-easyconfigs@d1adb4a](https://github.com/easybuilders/easybuild-easyconfigs/commit/d1adb4ae5a7af17b69a17dd75dd729fe1c56bb06) caused this issue

That change only touched `SYSTEM` toolchain versions of `ncurses` and the error above is in `ncurses/6.2-GCCcore-11.2.0`.

**Comment by Micket** [comment] 2022-09-16 09:20
It's actually the *lack* of doing the exact same fix for ncurses-6.2-GCCcore-11.2.0.eb (yet) which seems to be the cause here.

**Comment by elc42** [comment] 2022-09-17 07:07
@Micket:  Applying https://github.com/easybuilders/easybuild-easyconfigs/commit/d1adb4ae5a7af17b69a17dd75dd729fe1c56bb06 to ncurses-6.2-GCCcore-11.2.0.eb solves the problem

Thank you.

**Comment by boegel** [comment] 2022-10-26 07:18
This problem was indeed fixed in https://github.com/easybuilders/easybuild-easyconfigs/pull/16270, those changes are included with EasyBuild v4.6.2

**Closed by boegel** 2022-10-26 07:18 UTC
